from core.config import SUPABASE_URL, SUPABASE_SERVICE_KEY,OPENROUTER_API_KEY

print("SUPABASE_URL =", SUPABASE_URL)
print("SERVICE KEY =", SUPABASE_SERVICE_KEY[:10], "...")
print("Loaded:", OPENROUTER_API_KEY)
